backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
#markdown middleman blog example
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: page ID, name: pageid, widget: string}
      - {label: Author Name, name: authorName, widget: string}
      - {label: Author Position, name: authorPos, widget: string}
      - {label: Author Image, name: authorImage, widget: image}
      - {label: Body, name: body, widget: markdown}
      
      
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Story
            name: story
            widget: markdown
            
            

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
              - {label: ID, name: id, widget: string}
              - {label: Target, name: target, widget: string}
  - name: settings
    label: Settings
    files:
      - file: data/settings/newsletter.yml
        label: Newsletter
        name: newsletter
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Button Text, name: btnText, widget: string}
          - {label: Button Url, name: btnUrl, widget: string}
          - {label: Button Target, name: target, widget: string}
